[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "MetaModels Documentation"
authors = [{name = "Team MetaModels", email = "mail@metamodel.me"}]
dynamic = ["2.3", "MetaModels Dokumentation"]
